name = "website-test"
account_id = "d474ecbfe54a77cf62268270a18d22d8"

main = "./.svelte-kit/cloudflare/worker.js"
site.bucket = "./.svelte-kit/cloudflare"

build.command = "npm run build"

compatibility_date = "2021-11-12"
workers_dev = true